name: submission
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  go_router: ^15.1.2
  firebase_core: ^3.13.1
  google_sign_in_web: ^0.12.4+4
  firebase_auth: ^5.5.4
  flutter_riverpod: ^2.5.1 # Modern state management
  riverpod_annotation: ^2.3.5 # For code generation
  shared_preferences: ^2.0.15
  google_sign_in: ^6.0.0 # Google Sign-In integration
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

